/**
 * Jobs Styles
 * @format
 */

import { Colors, ITheme, ScaledSheet, Typography } from '@app/styles';
import { Platform } from 'react-native';

export const getStyles = (theme: ITheme) =>
  ScaledSheet.create({
    //Create Screen Styles
    container: {
        flex: 1,
        backgroundColor: Colors.background,
      },
      scrollView: {
        flex: 1,
      },
      scrollContent: {
        padding: 20,
        paddingBottom: 100,
      },
      header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
        marginTop:'5@ms',
      },
      headerBack: {
        paddingTop: '40@ms',
        paddingHorizontal: '24@ms',
      
      },
      backButton: {
        width: '40@ms',
        height: '40@ms',
        borderRadius: '20@ms',
        backgroundColor: Colors.backgroundCard,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: Colors.text,
        flex: 1,
        marginRight: 16,
      },
      statusContainer: {
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12@ms',
        // marginTop: '8@ms',
      },
      statusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
      },
      statusText: {
        color: Colors.white,
        fontWeight: '600',
        fontSize: 12,
      },
      description: {
        fontSize: 16,
        color: Colors.gray500,
        lineHeight: 24,
        marginBottom: 20,
      },
      communicationContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
      },
      communicationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.primary + '10',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        flex: 0.48,
      },
      communicationButtonText: {
        color: Colors.primary,
        fontWeight: '600',
        marginLeft: 8,
      },
      verificationContainer: {
        backgroundColor: Colors.backgroundCard,
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      verificationTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.text,
        marginBottom: 12,
      },
      verificationButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
        
      },
      verificationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.background,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        flex: 0.48,
      },
      verificationIcon: {
        marginRight: 8,
      },
      verificationButtonText: {
        color: Colors.text,
        fontWeight: '500',
        fontSize: '12@ms',
      },
      verificationButtonCompleted: {
        backgroundColor: Colors.success,
        opacity: 0.7,
      },
      verificationButtonTextCompleted: {
        color: Colors.white,
        opacity: 0.8,
      },
      paymentContainer: {
        backgroundColor: Colors.success + '10',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: Colors.success + '30',
      },
      paymentHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
      },
      paymentIcon: {
        marginRight: 8,
      },
      paymentTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.success,
      },
      paymentDescription: {
        fontSize: 14,
        color: Colors.gray700,
        lineHeight: 20,
        marginBottom: 16,
      },
      paymentDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: Colors.white,
        borderRadius: 8,
      },
      paymentLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: Colors.gray600,
      },
      paymentAmount: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.success,
      },
      compensationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.success + '10',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 8,
        marginBottom: 24,
        justifyContent: 'space-between',
      },
      compensationIcon: {
        marginRight: 8,
      },
      compensationText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.success,
      },
      bidsContainer: {
        backgroundColor: Colors.backgroundCard,
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      bidsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
      },
      bidsSectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.primary,
      },
      viewAllBidsButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: Colors.primary + '20',
        borderRadius: 16,
      },
      viewAllBidsText: {
        fontSize: 12,
        fontWeight: '600',
        color: Colors.primary,
      },
      showMoreBidsButton: {
        marginTop: 12,
        paddingVertical: 8,
        alignItems: 'center',
        backgroundColor: Colors.gray100,
        borderRadius: 8,
      },
      showMoreBidsText: {
        fontSize: 14,
        fontWeight: '500',
        color: Colors.primary,
      },
      bidItem: {
        backgroundColor: Colors.primary + '10',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 8,
        marginBottom: 12,
        borderLeftWidth: 4,
        borderLeftColor: Colors.primary,
      },
      bidHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
      },
      bidTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.primary,
      },
      bidStatus: {
        fontSize: 12,
        fontWeight: '500',
        color: Colors.error,
        backgroundColor: Colors.gray200,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        textTransform: 'capitalize',
      },
      bidAmount: {
        fontSize: 20,
        fontWeight: 'bold',
        color: Colors.primary,
        marginBottom: 8,
      },
      bidMessage: {
        fontSize: 14,
        color: Colors.textSecondary,
        fontStyle: 'italic',
        lineHeight: 20,
        marginBottom: 4,
      },
      bidNotes: {
        fontSize: 12,
        color: Colors.textMuted,
        marginBottom: 4,
      },
      bidDate: {
        fontSize: 12,
        color: Colors.textMuted,
        fontStyle: 'italic',
      },
      routeContainer: {
        backgroundColor: Colors.backgroundCard,
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      routePoint: {
        flexDirection: 'row',
        alignItems: 'flex-start',
      },
      routeMarker: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
      },
      pickupMarker: {
        backgroundColor: Colors.primary,
      },
      deliveryMarker: {
        backgroundColor: Colors.secondary,
      },
      routeInfo: {
        flex: 1,
      },
      routeLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.text,
        marginBottom: 4,
      },
      routeAddress: {
        fontSize: 16,
        color: Colors.text,
        marginBottom: 2,
      },
      routeCity: {
        fontSize: 14,
        color: Colors.gray600,
        marginBottom: 2,
      },
      routeTime: {
        fontSize: 14,
        color: Colors.gray500,
      },
      routeConnector: {
        width: 2,
        height: 30,
        backgroundColor: Colors.gray300,
        marginLeft: 15,
        marginVertical: 4,
      },
      detailsContainer: {
        backgroundColor: Colors.backgroundCard,
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
      },
      detailItem: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      detailIcon: {
        marginRight: 8,
      },
      detailLabel: {
        fontSize: 12,
        color: Colors.gray500,
        marginBottom: 2,
      },
      detailValue: {
        fontSize: 14,
        fontWeight: '500',
        color: Colors.text,
        
      },
      requirementsContainer: {
        backgroundColor: Colors.warning + '10',
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
      },
      requirementsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
      },
      requirementsIcon: {
        marginRight: 8,
      },
      requirementsTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.text,
      },
      requirementsText: {
        fontSize: 14,
        color: Colors.gray300,
        lineHeight: 20,
      },
      merchantContainer: {
        marginBottom: 24,
      },
      sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: Colors.text,
        marginBottom: 12,
      },
      merchantCard: {
        backgroundColor: Colors.backgroundCard,
        borderRadius: 12,
        padding: 16,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      merchantHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
      },
      merchantAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: Colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
      },
      merchantInfo: {
        flex: 1,
      },
      merchantName: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.white,
        marginBottom: 4,
      },
      merchantRating: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      merchantRatingText: {
        fontSize: 14,
        color: Colors.white,
        marginLeft: 4,
      },
      merchantContact: {
        flexDirection: 'row',
        justifyContent: 'space-around',
      },
      contactButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: Colors.primary,
        borderRadius: 8,
        minWidth: 100,
      },
      contactButtonText: {
        color: Colors.primary,
        fontWeight: '500',
        marginLeft: 8,
      },
      footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: Colors.backgroundCard,
        padding: 20,
        borderTopWidth: 1,
        // borderTopColor: Colors.gray200,
      },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    loadingText: {
      fontSize: 18,
      color: Colors.textSecondary,
      marginBottom: 20,
      textAlign: 'center',
    },
    messageContainer: {
      marginBottom: 16,
    },
    messageLabel: {
      fontSize: 16,
      fontWeight: '500',
      color: Colors.text,
      marginBottom: 8,
    },
    messageInput: {
      borderWidth: 1,
      borderColor: Colors.gray300,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: Colors.text,
      backgroundColor: Colors.backgroundCard,
      minHeight: 100,
      textAlignVertical: 'top',
    },
    // Bid Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    bidModalContainer: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: 16,
      margin: 20,
      maxHeight: '80%',
      width: '90%',
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    bidModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: Colors.border,
    },
    bidModalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.text,
    },
    closeButton: {
      padding: 4,
    },
    bidModalContent: {
      padding: 20,
    },
    bidJobTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: Colors.text,
      marginBottom: 8,
    },
    bidJobDescription: {
      fontSize: 14,
      color: Colors.textSecondary,
      marginBottom: 24,
      lineHeight: 20,
    },
    bidForm: {
      marginBottom: 24,
    },
    bidLabel: {
      fontSize: 16,
      fontWeight: '500',
      color: Colors.text,
      marginBottom: 8,
    },
    bidAmountContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 8,
      marginBottom: 16,
      backgroundColor: Colors.backgroundCard,
    },
    currencySymbol: {
      fontSize: 18,
      fontWeight: '600',
      color: Colors.text,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRightWidth: 1,
      borderRightColor: Colors.border,
    },
    bidAmountInput: {
      flex: 1,
      fontSize: 18,
      color: Colors.text,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    bidMessageInput: {
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: Colors.text,
      backgroundColor: Colors.backgroundCard,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    bidModalActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    cancelBidButton: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.border,
      alignItems: 'center',
    },
    cancelBidButtonText: {
      fontSize: 16,
      fontWeight: '500',
      color: Colors.textSecondary,
    },
    submitBidButton: {
      flex: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      backgroundColor: Colors.primary,
    },
    submitBidButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: Colors.white,
    },
    bidIcon: {
      marginRight: 8,
    },
    // Button Row Styles
    buttonRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
    },
    bidButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      backgroundColor: Colors.secondary,
      minWidth: 80,
    },
    bidButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: Colors.white,
    },
    buttonIcon: {
      marginRight: 8,
    },
    pickJobButton: {
      flex: 1,
    },
    jobId: {
      fontSize: "15@ms",
      fontWeight: "500",
      color: Colors.primary,
      opacity: 0.8,
    },
    tripTrackingButton: {
      backgroundColor: Colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: '10@ms',
      paddingHorizontal: '14@ms',
      borderRadius: '20@ms',
      marginLeft: '12@ms',
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
      minHeight: '36@ms',
    },
    tripTrackingButtonText: {
      fontSize: '13@ms',
      fontWeight: '600',
      color: Colors.white,
      marginLeft: '6@ms',
    },
    // Inspection styles
    inspectionContainer: {
      // backgroundColor: Colors.backgroundCard,
      borderRadius: '12@ms',
      // padding: '16@ms',
      marginBottom: '16@ms',
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    inspectionTitle: {
      fontSize: '18@ms',
      fontWeight: '600',
      color: Colors.text,
      marginBottom: '12@ms',
    },
    inspectionList: {
      gap: '10@ms',
    },
    inspectionItem: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: '8@ms',
      padding: '12@ms',
      // marginBottom: '12@ms',
    },
    inspectionType: {
      fontSize: '16@ms',
      fontWeight: '600',
      color: Colors.primary,
      marginBottom: '4@ms',
    },
    inspectionDate: {
      fontSize: '14@ms',
      color: Colors.gray600,
      marginBottom: '12@ms',
    },
    photosGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: '8@ms',
      marginBottom: '12@ms',
    },
    photoItem: {
      width: '31%',
      aspectRatio: 1,
    },
    inspectionPhoto: {
      width: '100%',
      height: '100%',
      borderRadius: '6@ms',
    },
    photoLabel: {
      fontSize: '12@ms',
      color: Colors.gray600,
      textAlign: 'center',
      marginTop: '4@ms',
    },
    podPhotoContainer: {
      marginTop: '8@ms',
    },
    podPhotoLabel: {
      fontSize: '14@ms',
      fontWeight: '600',
      color: Colors.success,
      marginBottom: '8@ms',
    },
    podPhoto: {
      width: '100%',
      height: '200@ms',
      borderRadius: '8@ms',
    },
    // Inspection status styles
    inspectionStatusContainer: {
      backgroundColor: Colors.success + '20',
      borderRadius: '8@ms',
      padding: '12@ms',
      marginTop: '12@ms',
      alignItems: 'center',
    },
    inspectionStatusText: {
      fontSize: '14@ms',
      fontWeight: '600',
      color: Colors.success,
    },
    // Comment display styles
    commentContainer: {
      marginTop: '12@ms',
      padding: '12@ms',
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
      borderRadius: '8@ms',
      borderLeftWidth: 3,
      borderLeftColor: Colors.primary,
    },
    commentLabel: {
      fontSize: '14@ms',
      fontWeight: '600',
      color: Colors.text,
      marginBottom: '4@ms',
    },
    commentText: {
      fontSize: '14@ms',
      color: Colors.gray200,
      lineHeight: '20@ms',
    },
    // Proof photos display styles
    proofPhotosSection: {
      marginTop: '12@ms',
      padding: '12@ms',
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
      borderRadius: '8@ms',
      borderLeftWidth: 3,
      borderLeftColor: Colors.success,
    },
    proofPhotosSectionTitle: {
      fontSize: '14@ms',
      fontWeight: '600',
      color: Colors.text,
      marginBottom: '8@ms',
    },
    proofPhotosGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    proofPhotoItem: {
      width: '31%',
      aspectRatio: 1,
      marginBottom: '8@ms',
      position: 'relative',
    },
    proofPhoto: {
      width: '100%',
      height: '100%',
      borderRadius: '6@ms',
      resizeMode: 'cover',
    },
    proofPhotoLabel: {
      position: 'absolute',
      bottom: '4@ms',
      left: '4@ms',
      right: '4@ms',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      color: Colors.white,
      fontSize: '12@ms',
      paddingHorizontal: '6@ms',
      paddingVertical: '2@ms',
      borderRadius: '4@ms',
      textAlign: 'center',
    },
    // Photo management styles
    photosContainer: {
      marginTop: '8@ms',
    },
    morePhotosButton: {
      width: '31%',
      aspectRatio: 1,
      // marginBottom: '10@ms',
      // position: 'relative',
    },
    morePhotosOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      borderRadius: '8@ms',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: Colors.primary,
      borderStyle: 'dashed',
    },
    morePhotosText: {
      color: Colors.white,
      fontSize: '18@ms',
      fontWeight: 'bold',
    },
    morePhotosSubtext: {
      color: Colors.white,
      fontSize: '12@ms',
      marginTop: '2@ms',
    },
    showLessButton: {
      alignSelf: 'center',
      marginTop: '12@ms',
      paddingHorizontal: '16@ms',
      paddingVertical: '8@ms',
      backgroundColor: Colors.primary,
      borderRadius: '20@ms',
    },
    showLessText: {
      color: Colors.white,
      fontSize: '14@ms',
      fontWeight: '500',
    },
    // Image modal styles
    imageModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.9)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageModalCloseButton: {
      position: 'absolute',
      top: '50@ms',
      right: '20@ms',
      width: '40@ms',
      height: '40@ms',
      borderRadius: '20@ms',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    fullSizeImage: {
      width: '90%',
      height: '80%',
      maxWidth: '400@ms',
      maxHeight: '600@ms',
    },
    // Debug styles
    debugSection: {
      backgroundColor: '#f0f0f0',
      padding: '10@ms',
      marginVertical: '5@ms',
      borderRadius: '5@ms',
      borderWidth: 1,
      borderColor: '#ddd',
    },
    debugTitle: {
      fontSize: '12@ms',
      fontWeight: 'bold',
      color: '#333',
      marginBottom: '5@ms',
    },
    debugText: {
      fontSize: '10@ms',
      color: '#666',
      marginBottom: '2@ms',
    },
    // New inspection tile styles
    inspectionTile: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: '12@ms',
      padding: '16@ms',
      marginBottom: '12@ms',
      borderLeftWidth: 4,
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    inspectionTileTitle: {
      fontSize: '16@ms',
      fontWeight: '600',
      color: Colors.text,
      marginBottom: '4@ms',
    },
    inspectionTileDate: {
      fontSize: '14@ms',
      color: Colors.gray600,
      marginBottom: '12@ms',
    },
    // Reshare Job Section Styles
    reshareContainer: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: '12@ms',
      padding: '20@ms',
      marginBottom: '16@ms',
      marginHorizontal: '4@ms',
      shadowColor: Colors.black,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    reshareHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: '12@ms',
    },
    reshareIcon: {
      width: '32@ms',
      height: '32@ms',
      borderRadius: '16@ms',
      backgroundColor: Colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: '12@ms',
    },
    reshareIconText: {
      fontSize: '16@ms',
    },
    reshareTitle: {
      fontSize: '18@ms',
      fontWeight: 'bold',
      color: Colors.warning,
      flex: 1,
    },
    reshareDescription: {
      fontSize: '14@ms',
      color: Colors.gray400,
      lineHeight: '20@ms',
      marginBottom: '16@ms',
    },
    reshareButton: {
      backgroundColor: Colors.warning,
      borderRadius: '8@ms',
      paddingVertical: '12@ms',
      paddingHorizontal: '20@ms',
      alignItems: 'center',
    },
    reshareButtonText: {
      fontSize: '16@ms',
      fontWeight: '600',
      color: Colors.white,
    },
  });
