/**
 * Profile Styles
 * @format
 */

import { Colors, ITheme, ScaledSheet } from '@app/styles';

export const getStyles = () =>
  ScaledSheet.create({
    //Docoment Screen Style
    container: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    header: {
      height: '140@ms',
      backgroundColor: Colors.primary,

      position: 'relative',
    },
    settingsButton: {
      position: 'absolute',
      top: 10,
      right: 20,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollView: {
      flex: 1,
      marginTop: -100,
    },
    scrollContent: {
      paddingBottom: '100@ms',
    },
    profileHeader: {
      alignItems: 'center',
      marginBottom: 24,
    },
    avatarContainer: {
      position: 'relative',
      marginBottom: 16,
    },
    avatar: {
      width: 120,
      height: 120,
      borderRadius: 60,
      borderWidth: 4,
      borderColor: Colors.white,
    },
    avatarPlaceholder: {
      backgroundColor: Colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarText: {
      fontSize: 48,
      fontWeight: 'bold',
      color: Colors.white,
    },
    editAvatarButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: Colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: Colors.white,
    },
    userName: {
      fontSize: 24,
      fontWeight: 'bold',
      color: Colors.text,
      marginBottom: 4,
    },
    userRole: {
      fontSize: 16,
      color: Colors.gray600,
      marginBottom: 12,
      textTransform: 'capitalize',
    },
    verificationBadge: {
      backgroundColor: Colors.success,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 16,
      marginBottom: 16,
    },
    verificationText: {
      color: Colors.white,
      fontSize: 12,
      fontWeight: '500',
    },
    notificationSection: {
      backgroundColor: Colors.backgroundLight,
      borderRadius: 12,
      padding: '16@ms',
      marginBottom: '24@ms',
      marginHorizontal: '20@ms',
    },
    notificationHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: '12@ms',
    },
    notificationIcon: {
      marginRight: '8@ms',
    },
    notificationTitle: {
      fontSize: '18@ms',
      fontWeight: '600',
      color: Colors.text,
    },
    notificationContent: {
      alignItems: 'center',
    },
    notificationText: {
      fontSize: '14@ms',
      color: Colors.textMuted,
      textAlign: 'center',
      marginBottom: '16@ms',
      lineHeight: '20@ms',
    },
    notificationButton: {
      minWidth: '120@ms',
    },
    editButton: {
      width: 150,
    },
    contactSection: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: 12,
      padding: 16,
      marginHorizontal: 20,
      marginBottom: 24,
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    contactItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    contactIcon: {
      marginRight: 12,
    },
    contactText: {
      fontSize: 16,
      color: Colors.text,
    },
    tabsContainer: {
      flexDirection: 'row',
      marginHorizontal: 20,
      marginBottom: 24,
      backgroundColor: Colors.backgroundLight,
      borderRadius: 12,
      paddingVertical: 4,
    },
    tabButton: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 8,
    },
    activeTabButton: {
      backgroundColor: Colors.primary,
    },
    tabButtonText: {
      fontSize: 12,
      fontWeight: '500',
      color: Colors.textSecondary,
    },
    activeTabButtonText: {
      color: Colors.white,
    },
    tabContent: {
      marginHorizontal: 20,
    },
    balanceSection: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: 12,
      padding: 16,
      marginHorizontal: 20,
      marginBottom: 24,
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    balanceItem: {
      marginBottom: 12,
    },
    balanceLabel: {
      fontSize: 14,
      color: Colors.gray500,
      marginBottom: 4,
    },
    balanceValue: {
      fontSize: 24,
      fontWeight: 'bold',
      color: Colors.success,
    },
    pendingValue: {
      fontSize: 18,
      fontWeight: '600',
      color: Colors.warning,
    },
    balanceActions: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 12,
    },
    balanceActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors.primary,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
    },
    actionIcon: {
      marginRight: 8,
    },
    actionText: {
      color: Colors.white,
      fontWeight: '500',
    },
    infoSection: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: 12,
      padding: 16,
      marginHorizontal: 20,
      marginBottom: 24,
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    infoRow: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    infoIcon: {
      marginRight: 12,
      marginTop: 2,
    },
    infoContent: {
      flex: 1,
    },
    infoLabel: {
      fontSize: 14,
      color: Colors.gray500,
      marginBottom: 4,
    },
    infoValue: {
      fontSize: 16,
      color: Colors.text,
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    ratingValue: {
      fontSize: 16,
      fontWeight: '600',
      color: Colors.text,
    },
    ratingIcon: {
      fontSize: 16,
      color: Colors.warning,
      marginLeft: 4,
    },
    ratingCount: {
      fontSize: 14,
      color: Colors.gray500,
      marginLeft: 8,
    },
    documentsSection: {
      marginHorizontal: 20,
      marginBottom: 24,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: Colors.text,
      marginBottom: 16,
    },
    manageDocsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.primaryLight,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: Colors.primary,
    },
    manageDocsText: {
      fontSize: 14,
      fontWeight: '500',
      color: Colors.white,
      marginLeft: 6,
    },
    documentItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.backgroundCard,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    documentIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: Colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    documentInfo: {
      flex: 1,
    },
    documentTitle: {
      fontSize: 16,
      fontWeight: '500',
      color: Colors.text,
      marginBottom: 4,
    },
    documentSubtitle: {
      fontSize: 14,
      color: Colors.gray500,
    },
    documentStatus: {
      marginTop: 4,
    },
    statusText: {
      fontSize: 12,
      fontWeight: '500',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
      alignSelf: 'flex-start',
    },
    statusVerified: {
      backgroundColor: Colors.success + '20',
      color: Colors.success,
    },
    statusPending: {
      backgroundColor: Colors.warning + '20',
      color: Colors.warning,
    },
    statusRejected: {
      backgroundColor: Colors.error + '20',
      color: Colors.error,
    },
    statusExpired: {
      backgroundColor: Colors.error + '20',
      color: Colors.error,
    },
    seeMoreDocuments: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      marginTop: 8,
    },
    seeMoreText: {
      fontSize: 14,
      color: Colors.primary,
      fontWeight: '500',
      marginRight: 4,
    },
    debugButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 20,
      marginTop: 8,
      marginBottom: 12,
      padding: 16,
      borderRadius: 12,
      backgroundColor: Colors.info + '10',
    },
    debugIcon: {
      marginRight: 8,
    },
    debugText: {
      fontSize: 16,
      fontWeight: '600',
      color: Colors.info,
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 20,
      marginTop: 8,
      marginBottom: 24,
      padding: 16,
      borderRadius: 12,
      backgroundColor: Colors.error + '10',
    },
    logoutIcon: {
      marginRight: 8,
    },
    logoutText: {
      fontSize: 16,
      fontWeight: '600',
      color: Colors.error,
    },
    // Transaction tab styles
    balanceCard: {
      backgroundColor: Colors.backgroundCard,
      borderRadius: 12,
      padding: 16,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    balanceHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    balanceCardLabel: {
      fontSize: 14,
      color: Colors.textSecondary,
    },
    balanceCardAmount: {
      fontSize: 28,
      fontWeight: 'bold',
      color: Colors.white,
      marginBottom: 8,
    },
    pendingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    pendingLabel: {
      fontSize: 14,
      color: Colors.textSecondary,
    },
    pendingAmount: {
      fontSize: 14,
      fontWeight: '600',
      color: Colors.warning,
    },
    seeAllText: {
      fontSize: 14,
      color: Colors.primary,
      fontWeight: '500',
    },
    transactionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.backgroundCard,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    transactionIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    transactionInfo: {
      flex: 1,
    },
    transactionTitle: {
      fontSize: 16,
      fontWeight: '500',
      color: Colors.white,
      marginBottom: 4,
    },
    transactionDate: {
      fontSize: 12,
      color: Colors.textSecondary,
    },
    transactionAmount: {
      alignItems: 'flex-end',
    },
    transactionAmountText: {
      fontSize: 16,
      fontWeight: '600',
      color: Colors.white,
      marginBottom: 4,
    },
    amountPositive: {
      color: Colors.success,
    },
    amountNegative: {
      color: Colors.error,
    },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
    },
    // Payment methods tab styles
    addButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.primary,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    addButtonText: {
      color: Colors.white,
      fontWeight: '500',
      fontSize: 12,
      marginLeft: 4,
    },
    paymentMethodItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.backgroundCard,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    selectedPaymentMethod: {
      borderColor: Colors.primary,
      backgroundColor: Colors.primary + '10',
    },
    paymentMethodIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: Colors.backgroundLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    paymentMethodInfo: {
      flex: 1,
    },
    paymentMethodTitle: {
      fontSize: 16,
      fontWeight: '500',
      color:   Colors.white,
      marginBottom: 4,
    },
    paymentMethodSubtitle: {
      fontSize: 12,
      color: Colors.textSecondary,
    },
    defaultBadge: {
      backgroundColor: Colors.primary + '20',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      marginRight: 8,
    },
    defaultText: {
      fontSize: 10,
      fontWeight: '500',
      color: Colors.primary,
    },
    selectedActions: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    actionButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
      marginTop: 20,
    },
    emptyStateTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: Colors.white,
      marginTop: 16,
      marginBottom: 8,
    },
    emptyStateDescription: {
      fontSize: 14,
      color: Colors.textSecondary,
      textAlign: 'center',
      marginBottom: 24,
    },
    emptyStateButton: {
      backgroundColor: Colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 8,
    },
    emptyStateButtonText: {
      color: Colors.white,
      fontWeight: '600',
    },
  
  });